<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>CGHHG</name>
  <uuid>42b2af64-5161-40d6-b3ed-d18c3d498a68</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to <a string> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
